# Generated by Django 3.1 on 2020-09-03 04:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0003_tweet_model_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet_model',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
